name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"   # runs daily at 3 AM UTC
  workflow_dispatch:       # allows manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Joydeep2005Banik/readme-stats-cards@v1
        with:
          username: Tirtha28
          token: ${{ secrets.GITHUB_TOKEN }}
